[global.databases]
main_db = {url = "postgres://admin:admin@localhost/ediary_db"}

[global.limits]
json = 33554432
file = 134217728

[default.tls]
certs = "tls/crt.pem"
key = "tls/key.pem"

[global.app]
redis_address = "redis://localhost:6379"
redis_module = "ediary"
token_secret_key = "N1/20?rHF3}I||Qc=!le[Whl(Pwvz5"
hash_secret_key = "M~3L*[lxi.^-/Q:w=Sgu@cxOXa))p#"